blank_issues_enabled: false
contact_links:
  - name: Start a discussion
    url: https://github.com/CryptocurrencyExplorer/CryptocurrencyExplorer/discussions
    about: General discussions
  - name: Questions?
    url: https://web.libera.chat/?channel=#cryptocurrencyexplorer
    about: Asynchronous chat with the dev, when available
